name: build and archive

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: set up zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
          cd server
          zig build
      - run: |
          cd app
          zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseSafe
      - name: Archive upload
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/zig-out/bin/app.exe

          if-no-files-found: warn
          overwrite: true
